import type { LocalRule } from "./types";

export const RULES: LocalRule[] = [
  // Homophones
  {
    id: "their-there",
    pattern: /\btheir\b(?=\s+(is|are|was|were|will|going))/gi,
    type: "grammar",
    suggestion: "there",
    explanation: "'Their' is possessive. Use 'there' for places/existence.",
  },
  {
    id: "your-youre",
    pattern: /\byour\b(?=\s+(a |the |going|welcome|right|wrong|not|never))/gi,
    type: "grammar",
    suggestion: "you're",
    explanation: "'Your' is possessive. Use 'you're' (you are) here.",
  },
  {
    id: "its-its",
    pattern: /\bit's\b(?=\s+(own|self|way|place|time|color|size))/gi,
    type: "grammar",
    suggestion: "its",
    explanation: "'It's' = 'it is'. Use 'its' for possession.",
  },
  {
    id: "hear-here-1",
    pattern: /\b(come|over|right|up|around|from|near|out|in|down|click|tap|look) hear\b/gi,
    type: "grammar",
    suggestion: "$1 here",
    explanation: "'Hear' means to listen. Use 'here' for location.",
  },
  {
    id: "here-hear",
    pattern: /\bhere (me|us|him|her|them|that|this|it) out\b/gi,
    type: "grammar",
    suggestion: "hear $1 out",
    explanation: "'Here' is a location. Use 'hear' for listening.",
  },
  {
    id: "affect-effect",
    pattern: /\b(the|a|an|this|that|its|no|any|positive|negative|big|huge|major|side) affect\b/gi,
    type: "grammar",
    suggestion: "$1 effect",
    explanation: "'Affect' is usually a verb. Use 'effect' as a noun.",
  },
  {
    id: "then-than",
    pattern: /\b(more|less|better|worse|greater|bigger|smaller|faster|slower|rather|other) then\b/gi,
    type: "grammar",
    suggestion: "$1 than",
    explanation: "Use 'than' for comparisons, 'then' for time/sequence.",
  },
  {
    id: "accept-except",
    pattern: /\baccept\b(?=\s+(for|that|when|if|in))/gi,
    type: "grammar",
    suggestion: "except",
    explanation: "'Accept' means to receive. Use 'except' for exclusions.",
  },
  {
    id: "loose-lose",
    pattern: /\b(don't|didn't|won't|wouldn't|going to|gonna|might|will|could|can't) loose\b/gi,
    type: "grammar",
    suggestion: "$1 lose",
    explanation: "'Loose' means not tight. Use 'lose' for misplacing/failing.",
  },
  {
    id: "could-of",
    pattern: /\bcould of\b/gi,
    type: "grammar",
    suggestion: "could have",
    explanation: "'Could of' is a mishearing of 'could have' or 'could've'.",
  },
  {
    id: "should-of",
    pattern: /\bshould of\b/gi,
    type: "grammar",
    suggestion: "should have",
    explanation: "'Should of' should be 'should have' or 'should've'.",
  },
  {
    id: "would-of",
    pattern: /\bwould of\b/gi,
    type: "grammar",
    suggestion: "would have",
    explanation: "'Would of' should be 'would have' or 'would've'.",
  },
  {
    id: "doubled-word",
    pattern: /\b(\w+)\s+\1\b/gi,
    type: "grammar",
    suggestion: "$1",
    explanation: "Repeated word detected.",
  },
  {
    id: "he-dont",
    pattern: /\b(he|she|it) don't\b/gi,
    type: "grammar",
    suggestion: "$1 doesn't",
    explanation: "Use 'doesn't' with he/she/it.",
  },
  {
    id: "they-was",
    pattern: /\bthey was\b/gi,
    type: "grammar",
    suggestion: "they were",
    explanation: "'They' takes 'were', not 'was'.",
  },
  {
    id: "double-period",
    pattern: /\.{2}(?!\.)/g,
    type: "grammar",
    suggestion: ".",
    explanation: "Double period detected.",
  },
  {
    id: "no-space-after-period",
    pattern: /\.([A-Z])/g,
    type: "grammar",
    suggestion: ". $1",
    explanation: "Add a space after the period.",
  },
];
